name: MyCI
on:
  workflow_dispatch:
jobs:
  steps:
  - name: Read package.json
    id: package
    uses: juliangruber/read-file-action@v1
    with:
      path: ./package.json
  - name: Echo package.json
    run: echo "${{ steps.package.outputs.content }}"
